Concert/Areas/Admin/Controllers/GenreController.cs
using Concert.DataAccess.Data;
using Concert.DataAccess.Repository.IRepository;
using Concert.Models;
using Concert.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ConcertWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.ROLE_ADMIN)]
    public class GenreController : BaseController
    {
        private readonly IUnitOfWork _unitOfWork;

        public GenreController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<Genre> genreList = _unitOfWork.Genre.GetAll().ToList();

            return View(genreList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Genre genre)
        {
            ValidateGenre(genre);

            if (ModelState.IsValid)
            {
                _unitOfWork.Genre.Add(genre);
                _unitOfWork.Save();
                TempData["success"] = "Genre created successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Genre? genreFromDb = _unitOfWork.Genre.Get(u => u.Id == id);

            if (genreFromDb == null)
            {
                return NotFound();
            }

            return View(genreFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Genre genre)
        {
            ValidateGenre(genre);

            if (ModelState.IsValid)
            {
                _unitOfWork.Genre.Update(genre);
                _unitOfWork.Save();
                TempData["success"] = "Genre updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Genre? genreFromDb = _unitOfWork.Genre.Get(u => u.Id == id);

            if (genreFromDb == null)
            {
                return NotFound();
            }

            return View(genreFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            Genre? genre = _unitOfWork.Genre.Get(u => u.Id == id);

            if (genre == null)
            {
                return NotFound();
            }

			var songsWithThisGenre = _unitOfWork.Song.GetAll(u => u.GenreId == id).ToList();

			if (songsWithThisGenre.Count() > 0)
			{
				TempData["warning"] = "You cannot delete this genre because it's already used in some songs";
			}
			else
			{
				_unitOfWork.Genre.Remove(genre);
				_unitOfWork.Save();
				TempData["success"] = "Genre deleted successfully";
			}

			
            return RedirectToAction("Index");
        }

        private void ValidateGenre(Genre genre)
        {
            if (genre.Name.Any(char.IsDigit))
            {
                ModelState.AddModelError("Name", "The Name can contain letters only.");
            }
        }
    }
}

Concert/Areas/Admin/Views/Genre/Create.cshtml
<!-- It creates a new Genre object -->
@model Genre

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Genre</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <div class="border p-3">
                <div class="form-floating py-2 col-12">
                    <input asp-for="Name" class="form-control border-0 shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DisplayOrder" class="form-control border-0 shadow" />
                    <label asp-for="DisplayOrder" class="ms-2"></label>
                    <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Create</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-area="Admin" asp-controller="Genre" asp-action="Index" class="btn btn-outline-secondary border form-control">
                            Back to List
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Concert/Areas/Admin/Views/Genre/Delete.cshtml
<!-- It creates a new Genre object -->
@model Genre

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Genre</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <input asp-for="Id" hidden />
            <div class="border p-3 mt-4">
                <div class="form-floating py-2 col-12">
                    <input asp-for="Name" disabled class="form-control border-0 shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DisplayOrder" disabled class="form-control border-0 shadow" />
                    <label asp-for="DisplayOrder" class="ms-2"></label>
                </div>
                <div class="row mt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger form-control">Delete</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-area="Admin" asp-controller="Genre" asp-action="Index" class="btn btn-outline-secondary border form-control">
                            Back to List
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

Concert/Areas/Admin/Views/Genre/Edit.cshtml
<!-- It creates a new Genre object -->
@model Genre

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Edit Genre</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <input asp-for="Id" hidden />
            <div class="border p-3 mt-4">
                <div class="form-floating py-2 col-12">
                    <input asp-for="Name" class="form-control border-0 shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DisplayOrder" class="form-control border-0 shadow" />
                    <label asp-for="DisplayOrder" class="ms-2"></label>
                    <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                </div>
                <div class="row mt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Update</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-area="Admin" asp-controller="Genre" asp-action="Index" class="btn btn-outline-secondary border form-control">
                            Back to List
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Concert/Areas/Admin/Views/Genre/Index.cshtml
@model List<Genre>

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Genre List</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-4">
            <div class="col-12 text-end">
                <a asp-area="Admin" asp-controller="Genre" asp-action="Create" class="btn btn-primary">
                    <i class="bi bi-plus-square"></i> Create new Genre
                </a>
            </div>
        </div>
        <!-- Table -->
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Music Genre</th>
                    <th>Display Order</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var genre in Model.OrderBy(u => u.DisplayOrder))
                {
                    <tr>
                        <td>@genre.Name</td>
                        <td>@genre.DisplayOrder</td>
                        <td>
                            <div class="w-50 btn-group" role="group">
                                <a asp-area="Admin" asp-controller="Genre" asp-action="Edit" asp-route-id="@genre.Id" class="btn btn-primary mx-1">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-area="Admin" asp-controller="Genre" asp-action="Delete" asp-route-id="@genre.Id" class="btn btn-danger mx-1">
                                    <i class="bi bi-trash3"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>